name: eg201112469957
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.6.0
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  get_it: ^7.7.0
  uuid: ^4.4.2
  responsive_framework: ^1.4.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  go_router: ^14.2.3
  logger: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  intl_phone_field: ^3.2.0
  awesome_dialog: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
